[package]
name = "kidsviewer"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"
#garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.18.1" }
# Change to just "openzeppelin" to use full features
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
cairo_test = "2.12.0"
openzeppelin_utils = "1.0.0"
snforge_std = "0.48.1"

[profile.dev]
opt-level = 0

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[profile.release]
opt-level = 3

[profile.release.cairo]
inlining-strategy = 2

[cairo]
sierra-replace-ids = false
inlining-strategy = 2
allowed-libfuncs-list = { version = "2.12.0" }

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
